### PR TITLE
Update runtime to 23.08

### PR DESCRIPTION
**Pull request by bbhtt**

### CODE REVIEW

**Comment by bbhtt** [comment]
Runs

**Comment by ghost** [comment]
Any action

**Comment by bbhtt** [comment]
> Any action

Can you submit an EOL PR? It seems the maintainer deleted their Github account. There's little point in continuing to merge updates here.

**Comment by bbhtt** [comment]
Done via https://github.com/flathub/org.homelinuxserver.vance.biblereader/pull/5

**Pull request closed without merging**
